channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=25.1.1
- pip:
  - mlflow<3,>=2.2
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==11.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.0
name: mlflow-env
